### PR TITLE
Bug fix and equatable CameraType

### PR DESCRIPTION
**Pull request by maysamsh**
On front camera request flashMode to be turned on caused a crash. Fixed.
CameraType is conformed to Equatable protocol.

### CODE REVIEW

**Review by tomw — CHANGES_REQUESTED** [review]
Thanks. Your change on lines 248/256 isn't needed I don't think, I've already made them in a slightly more concise way. I have the condition inline at the end of the if statement.

Making it hashable is good, but maybe a better way would be to make the enum of type string, make each value equal some string like "front", then have the hash value return the hash value for that string (using self.rawValue, and removing the if statement). That way the keys will be more useful when debugging, and the compiler won't allow duplicates by mistake as this if statement would.

**Comment by maysamsh** [comment]
I think having it equatable would be useful.

**Comment by tomw** [comment]
Yeah sure, we can just compare rawValue instead

**Comment by maysamsh** [comment]
All right sir, if you say so. One more thing, to solve the crash problem I just updated the capture func to this:

    public func capturePhoto(imageStabilization: Bool = true, flashMode: AVCaptureFlashMode = .auto) {
        
        guard let photoOutput = self.photoOutput else { return }
        
        let captureSettings = AVCapturePhotoSettings(format: [ AVVideoCodecKey : AVVideoCodecJPEG ])
        if cameraType == .back {
            captureSettings.flashMode = flashMode
        }
        
        captureSettings.isAutoStillImageStabilizationEnabled = imageStabilization
        captureSettings.isHighResolutionPhotoEnabled = true
        
        photoOutput.capturePhoto(with: captureSettings, delegate: self)
        
    }
}

**Comment by tomw** [comment]
Thanks for the info. Please see v1.1.3

**Pull request closed without merging**
